### PR TITLE
Add some flexibility to how xword-dl saves files

### PR DESCRIPTION
**Pull request by blandford**
This will let you save into other directories (eg. 'xword-dl -o /tmp/temp.puz') as well as let you output the .puz file directly to stdout.

### CODE REVIEW

**Review by thisisparker — APPROVED** [review]

**Review by thisisparker — COMMENTED** [review]
Totally into the `-` case but I want to make sure that removing `/` from the exclusion list doesn't have any weird effects. Like, might xword-dl suggest a filename for a puzzle titled "Either/Or" that ends up saving in an "`Either`" directory? Should I just guard against that in the BaseDownloader's name picking method?

**Comment by thisisparker** [comment]
Lol also can you tell I have no idea how to work Github

**Comment by blandford** [comment]
Hey Parker,

I see what you mean by wanting to guard against '/' characters. I moved the call to remove invalid chars to just remove the fields from the puzzle, before we do the substitution. That will guard against unexpected (and potentially problematic) shell characters, but still permit intended ones.

If someone wants to call the output file /tmp/<>"\|?*.puz I suppose we should let them!!?

**Comment by blandford** [comment]
Just a friendly reminder on this issue. I'm hoping you can get this into the next release, when it happens.

**Pull request merged**
