### PR TITLE
New amuselabs obfuscation

### PR DESCRIPTION
**Pull request by boisvert42**
It works on all the ones I've tested it on, but I suspect they will change things again shortly.

### CODE REVIEW

**Comment by boisvert42** [comment]
Yeah, that's perfect. I basically made this as a placeholder. I'll keep checking on it.

**Comment by boisvert42** [comment]
They did in fact change things in the way I thought they would so I'm now pulling in the JS to find the decode key they're using.

**Comment by edsantiago** [comment]
Can confirm: New Yorker 2022-06-20 (today) fails to download:
```
'utf-8' codec can't decode byte 0x94 in position 0: invalid start byte
```
This patch resolves the problem. Thank you @boisvert42 .

**Comment by thisisparker** [comment]
Alright, let's do it! Thank you @boisvert42.

**Pull request merged**
